---
apiVersion: v1
kind: Service
metadata:
  name: fast-app-service
  namespace: default
spec:
  selector:
    app: fast-app
  type: LoadBalancer      # gives you an external AWS ELB
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000