---
- name: Ensure required packages are installed
  dnf:
    name:
    - unzip
    - git
    state: present

- name: Install AWS CLI v2
  shell: |
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"
    unzip -o /tmp/awscliv2.zip -d /tmp
    /tmp/aws/install --update
  args:
    creates: /usr/local/bin/aws

- name: Get latest kubectl version
  uri:
    url: https://dl.k8s.io/release/stable.txt
    return_content: yes
  register: kubectl_version

- name: Download kubectl binary directly
  get_url:
    url: "https://dl.k8s.io/release/{{ kubectl_version.content | trim }}/bin/linux/amd64/kubectl"
    dest: /usr/local/bin/kubectl
    mode: '0755'
    force: false

- name: Verify kubectl installed
  command: kubectl version --client
  register: kubectl_out
  changed_when: false

- name: Print kubectl version
  debug:
    msg: "{{ kubectl_out.stdout }}"

- name: Configure kubeconfig for EKS
  shell: |
    aws eks update-kubeconfig \
      --name {{ eks_cluster_name }} \
      --region {{ aws_region }}
  become_user: ec2-user
  ignore_errors: true

- name: Deploy app to Kubernetes
  shell: |
    kubectl apply -f /home/ec2-user/k8s/
  become_user: ec2-user
  ignore_errors: true
