name: Deploy Entire Infra

on:
  push:
    branches: [feat-dev]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false

    - name: Create terraform.tfvars
      working-directory: ./terraform
      run: |
        cat > terraform.tfvars <<EOF
        region                  = "${{ secrets.AWS_REGION }}"
        ami                     = "${{ secrets.AMI_ID }}"
        instance_type           = "${{ secrets.INSTANCE_TYPE }}"
        instance-name-nginx     = "${{ secrets.INSTANCE_NAME_NGINX }}" 
        vpc_name                = "${{ secrets.VPC_NAME }}"
        EOF
 
 
    - name: Terraform Init

      run: terraform init 

    - name: Terraform Plan 
      working-directory: ./terraform
      run: terraform plan -out=tfplan

    - name: Terraform Apply --var-file=terraform.tfvars --auto-approve 
      working-directory: ./terraform
      run: terraform apply -auto-approve tfplan   

