name: Deploy Entire Infra

on:
  push:
    branches: [feat-dev]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false

    - name: Create terraform.tfvars
      working-directory: ./terraform
      run: |
        cat > terraform.tfvars <<EOF
        region                  = "${{ secrets.AWS_REGION }}"
        ami                     = "${{ secrets.AMI_ID }}"
        instance_type           = "${{ secrets.INSTANCE_TYPE }}"
        instance-name-nginx     = "${{ secrets.INSTANCE_NAME_NGINX }}" 
        vpc_name                = "${{ secrets.VPC_NAME }}"

        key_name              =  "${{ secrets.KEY_NAME }}"  
        EOF
 
 
    - name: Terraform Init
      working-directory: ./terraform
      run: terraform init 

    - name: Terraform Plan 
      working-directory: ./terraform
      run: terraform plan -out=tfplan

    - name: Terraform Apply --var-file=terraform.tfvars --auto-approve 
      working-directory: ./terraform
      run: terraform apply -auto-approve tfplan   

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, Tag and Push image to ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: fast-app-repo
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          
          # Also tag as latest
        docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT


    - name: Update kubeconfig for EKS
      run: |
        aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}


    - name: Deploy to EKS
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: | 
        sed -i "s|my-image|$ECR_REGISTRY/fast-app-repo:$IMAGE_TAG|g" k8s/deploy.yml
        kubectl apply -f k8s/deploy.yml
        kubectl apply -f k8s/service.yml
         # Wait for rollout to finish
        kubectl rollout status deployment/fast-app --timeout=120s
      # ---- Print the external URL ----
    - name: Get Load Balancer URL
      run: |
        kubectl get service fast-app-service \
        -o jsonpath='{.status.loadBalancer.ingress[0].hostname}'