name: Deploy Entire Infra

on:
  push:
    branches: [feat-dev]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false

    - name: Create terraform.tfvars
      run: |
        cat > terraform.tfvars <<EOF
        aws_region                  = "${{ vars.AWS_REGION }}"
        ami                     = "${{ vars.AMI_ID }}"
        instance_type           = "${{ vars.INSTANCE_TYPE }}"
        instance-name-nginx     = "${{ vars.INSTANCE_NAME_NGINX }}" 
        vpc_name                = "${{ vars.VPC_NAME }}"
        EOF
 
 
    - name: Terraform Init
      run: terraform init 

    - name: Terraform Plan
      run: terraform plan -out=tfplan 

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan   

